sudo: required

services:
  - docker

before_install:
  - docker build -t test-service .

script:
  - docker run -P test-service google.com output.pdf
  - pdftotext -layout output.pdf - | grep -q Google
